// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Engls/forum-project2/forum_service/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ChatRepository is an autogenerated mock type for the ChatRepository type
type ChatRepository struct {
	mock.Mock
}

// GetRecentMessages provides a mock function with given fields: ctx, limit
func (_m *ChatRepository) GetRecentMessages(ctx context.Context, limit int) ([]entity.ChatMessage, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentMessages")
	}

	var r0 []entity.ChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.ChatMessage, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.ChatMessage); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ChatMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreMessage provides a mock function with given fields: ctx, msg
func (_m *ChatRepository) StoreMessage(ctx context.Context, msg entity.ChatMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for StoreMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ChatMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChatRepository creates a new instance of ChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatRepository {
	mock := &ChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
