// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/miqxzz/miqxzzforum/forum_service/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CommentsUsecases is an autogenerated mock type for the CommentsUsecases type
type CommentsUsecases struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: ctx, comment
func (_m *CommentsUsecases) CreateComment(ctx context.Context, comment entity.Comment) (entity.Comment, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 entity.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Comment) (entity.Comment, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Comment) entity.Comment); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Get(0).(entity.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetComments provides a mock function with given fields: ctx, postID, limit, offset
func (m *CommentsUsecases) GetComments(ctx context.Context, postID, limit, offset int) ([]entity.Comment, error) {
	args := m.Called(ctx, postID, limit, offset)
	var r0 []entity.Comment
	if args.Get(0) != nil {
		r0 = args.Get(0).([]entity.Comment)
	}
	return r0, args.Error(1)
}

// GetTotalCommentsCount provides a mock function with given fields: ctx, postID
func (m *CommentsUsecases) GetTotalCommentsCount(ctx context.Context, postID int) (int, error) {
	args := m.Called(ctx, postID)
	return args.Int(0), args.Error(1)
}

// NewCommentsUsecases creates a new instance of CommentsUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentsUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentsUsecases {
	mock := &CommentsUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
