// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Engls/forum-project2/forum_service/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CommentsUsecases is an autogenerated mock type for the CommentsUsecases type
type CommentsUsecases struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: ctx, comment
func (_m *CommentsUsecases) CreateComment(ctx context.Context, comment entity.Comment) (entity.Comment, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 entity.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Comment) (entity.Comment, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Comment) entity.Comment); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Get(0).(entity.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommentByPostID provides a mock function with given fields: ctx, postId
func (_m *CommentsUsecases) GetCommentByPostID(ctx context.Context, postId int) ([]entity.Comment, error) {
	ret := _m.Called(ctx, postId)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByPostID")
	}

	var r0 []entity.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.Comment, error)); ok {
		return rf(ctx, postId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.Comment); ok {
		r0 = rf(ctx, postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentsUsecases creates a new instance of CommentsUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentsUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentsUsecases {
	mock := &CommentsUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
